[[creds]]
endpoint="https://<azurecommApplication>.communication.azure.com/"
keyName="<key_name>"
key = "<key==>"
connection_string = "<connection_string>"
mailFrom="<azureEmailaddress>.azurecomm.net"
